---
driver:
  name: vagrant

provisioner:
  # name of the host
  hosts: test-kitchen
  # use an ansible playbook to provision our server
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_version: {{ cookiecutter.ansible_version }}
  require_chef_for_busser: false
  require_chef_for_busser: false
  sudo: true

platforms:
  - name: ubuntu-16.04

verifier:
  name: serverspec
  sudo_path: {{ cookiecutter.role_use_sudo }}

suites:
  # suites found at /test/integration/$test-name
  - name: default
