---
driver:
  name: docker
  use_sudo: false

provisioner:
  # name of the host
  hosts: test-kitchen
  # use an ansible playbook to provision our server
  name: ansible_playbook
  ansible_verbose: false
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_version: {{ cookiecutter.ansible_version }}
  require_chef_for_busser: false
  sudo: {{ cookiecutter.role_use_sudo }}

transport:
  max_ssh_sessions: 6

platforms:
  - name: ubuntu-rolling
    driver_config:
      run_command: /lib/systemd/systemd
      dockerfile: .docker/ubuntu/rolling/Dockerfile
      platform: ubuntu
      instance_name: test-role-{{ cookiecutter.role_name }}-ubuntu-rolling
      cap_add:
        - SYS_ADMIN
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_options:
        tmpfs:
          - /run
          - /run/lock

  - name: ubuntu-stable
    driver_config:
      run_command: /lib/systemd/systemd
      dockerfile: .docker/ubuntu/stable/Dockerfile
      platform: ubuntu
      instance_name: test-role-{{ cookiecutter.role_name }}-ubuntu-stable
      cap_add:
        - SYS_ADMIN
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_options:
        tmpfs:
          - /run
          - /run/lock

  - name: debian-stable
    driver_config:
      run_command: /lib/systemd/systemd
      dockerfile: .docker/debian/stable/Dockerfile
      platform: debian
      instance_name: test-role-{{ cookiecutter.role_name }}-debian-stable
      cap_add:
        - SYS_ADMIN
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_options:
        tmpfs:
          - /run
          - /run/lock

  - name: debian-oldstable
    driver_config:
      run_command: /lib/systemd/systemd
      dockerfile: .docker/debian/oldstable/Dockerfile
      platform: debian
      instance_name: test-role-{{ cookiecutter.role_name }}-debian-oldstable
      cap_add:
        - SYS_ADMIN
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_options:
        tmpfs:
          - /run
          - /run/lock

  - name: fedora-latest
    driver_config:
      run_command: /lib/systemd/systemd
      dockerfile: .docker/fedora/latest/Dockerfile
      platform: fedora
      instance_name: test-role-{{ cookiecutter.role_name }}-fedora-latest
      cap_add:
        - SYS_ADMIN
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_options:
        tmpfs:
          - /run
          - /run/lock

  - name: opensuse-tumbleweed
    driver_config:
      run_command: /usr/lib/systemd/systemd
      dockerfile: .docker/opensuse/tumbleweed/Dockerfile
      platform: opensuse
      instance_name: test-role-{{ cookiecutter.role_name }}-opensuse-tumbleweed
      cap_add:
        - SYS_ADMIN
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_options:
        tmpfs:
          - /run
          - /run/lock

verifier:
  name: serverspec
  sudo_path: {{ cookiecutter.role_use_sudo }}

suites:
  # suites found at /test/integration/$test-name
  - name: default
    verifier:
      patterns:
        - roles/{{ cookiecutter.role_name }}/test/integration/default/serverspec/*_spec.rb
